---
title: "Untitled"
author: "Matt Higham"
date: "11/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
nfl_df <- read_csv("nfl_games_historical.csv")
nfl_2018 <- nfl_df %>% mutate(year = year(date)) %>%
  filter(season == 2018) 
nfl_2018 %>% mutate(result2 = 1 - result1) %>% unite("item1", c(team1, elo1, score1, result1), sep = "--") %>%
  unite("item2", c(team2, elo2, score2, result2), sep = "--") %>%
  pivot_longer(c(item1, item2), names_to = "team", values_to = "value") %>%
  select(team, value, everything()) %>%
  separate(value, into = c("team", "elo", "score", "result"), sep = "--", convert = TRUE) 

## group by team and keep the max date
## define a season variable....this will differ for the different
## domains but you should have some idea about the start month for 
## each season and the end month for each season so you can use
## that to your advantage!

library(tidyverse)
df <- tibble(thing1 = c(1, 3, 2), thing2 = c(5, 1, 3),
       place1 = c("a", "b", "c"), place2 = c("d", "e", "f"))
df %>% unite("stuffs1", c(thing1, place1), sep = "--") %>%
  unite("stuffs2", c(thing2, place2), sep = "--") %>%
  pivot_longer(c(stuffs1, stuffs2), names_to = "names", values_to = "value") %>%
  separate(value, into = c("thing", "place"), sep = "--", convert = TRUE) 
df %>% pivot_longer(c(thing1, thing2, place1, place2), 
                    names_to = c("test1", "test2"),
                   names_pattern = "([A-Za-z]+)(\\d+)")
df %>% pivot_longer(c(thing1, thing2),
                    names_to = "test1",
                    values_to = "test2") %>%
  pivot_longer(c(place1, place2))
## want to do this but with pivot_longer() 
## need to use names_to argument but can't figure it out

nfl_2018_1 <- nfl_2018 %>% select(date, season, neutral, playoff, team1, elo1, elo_prob1, score1, result1, year)
nfl_2018_2 <- nfl_2018 %>% select(date, season, neutral, playoff, team2, elo2, elo_prob1, score2, result1, year)
nfl_2018_2 <- nfl_2018_2 %>% rename(team1 = "team2", elo1 = "elo2", score1 = "score2")
nfl2018_long <- bind_rows(nfl_2018_1, nfl_2018_2)

ggplot(data = nfl2018_long, aes(x = date, y = elo1)) + 
  geom_line(aes(group = team1))

```

```{r}
nfl2018_tidy <- nfl2018_long %>%
  mutate(weekvar = week(date)) %>%
  group_by(weekvar) %>%
  mutate(rankelo = rank(desc(elo1))) %>%
  select(weekvar, rankelo, everything()) %>%
  filter(rankelo <= 10) %>%
  ungroup() %>% group_by(weekvar) %>%
  mutate(teamord = fct_reorder(team1, rankelo))

anim <- ggplot(nfl2018_tidy, aes(x = elo1, y = fct_reorder(teamord, .x = elo1), group = weekvar)) +
  geom_col() + transition_states(weekvar, transition_length = 1, state_length = 1)## +
##  view_follow(fixed_x = TRUE)

animate(anim, 200, fps = 20,  width = 1200, height = 1000, 
        renderer = gifski_renderer("gganim.gif"))

ggplot(nfl2018_tidy, aes(x = rankelo, group = team1, 
                fill = as.factor(team1), color = as.factor(team1))) 


+
  geom_tile(aes(y = value/2,
                height = value,
                width = 0.9), alpha = 0.8, color = NA) 

# The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = rank(-value),
         Value_rel = value/value[rank==1],
         Value_lbl = paste0(" ",round(value/1e9))) %>%
  group_by(country_name) %>% 
  filter(rank <=10) %>%
  ungroup()

staticplot = ggplot(nfl2018_long, aes(x = rank, group = team, 
                fill = as.factor(country_name), color = as.factor(country_name))) +
  geom_tile(aes(y = value/2,
                height = value,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(country_name, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=value,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
         axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
       plot.margin = margin(2,2, 2, 4, "cm"))
```


