---
title: "Week 6: Midterm 1 Study Guide"
author: "Matt Higham"
output: 
  rmdformats::readthedown:
    code_folding: hide
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You should be able to do the following in order to be successful on the first midterm exam. Additionally, you should understand __when__ to use each of the following. Questions may not be phrased like: "Use `filter()` to choose rows in the data set such that `x < 10`." Instead, most questions will be phrased like: "Create a data set that only keeps the rows where `x < 10`," and you'll have to know that you need to use `filter()`.

Use the study guide to help you review any topics you may need a refresher on with previous exercises. My advice would be to complete these exercises __without__ looking at your previous work or at the solutions.

## General

* Interpret any plots or tables that you make in context of the problem.

## Week 1: `ggplot2`

* Construct a 
    * histogram and a frequency plot for exploration of a quantitative variable
    * scatterplot for exploration of two quantitative variables, perhaps adding a smoother or a linear regression line
    * faceted scatterplot for exploration of two quantitative variables and a categorical variable or two (the facet(s)), perhaps adding a smoother or a linear regression line
    * line plot for exploration of two quantitative variables (with one variable typically being time)
    * side-by-side boxplot for exploration of a categorical variable and a quantitative variable
    * barplot for exploration of a single categorical variable
    * stacked barplot or side-by-side barplot for exploration of two categorical variables
    
* change `aes()` options, including colour, size, shape, fill, and linetype

* change non-`aes()` options, including colour, size, shape, alpha, bins, span, fill, and linetype (and understand when you'd want to change options inside vs. outside the aesthetics).

* change options either globally or locally, depending on the question.

## Week 2: `dplyr`

* use the `mutate()` function, perhaps with `if_else()` or `case_when()` to create a new variable.

* use `filter()` or `slice()` to choose rows and `select()` to choose columns

* use `arrange()` to order the rows.

* use `summarise()` (perhaps paired with `group_by()`) to find a (grouped) summary statistic. Within `summarise()`, also use the `n()` function to find a count. 

* with all of these functions, use arguments to drop `NA` values when necessary, appropriately use Boolean operators (`&`, `|`), use arithmetic operators (`+`, `-`, `*`, etc.), comparison operators (`<`, `==`, `!=`, etc.), use piping (`%>%`) to string together multiple functions.

## Week 3: `tidyr`

* Describe what it means for a data set to be `tidy` and recognize an untidy data set.

* Use `separate()` and/or `unite()` to help tidy a data set.

* Use `pivot_wider()` and `pivot_longer()` to help tidy a data set.

* Use `rename()` to rename the columns of a data set.

* Use `parse_number()` to get rid of units within observations of a data set.

## Week 4: `R Markdown` and `ggplot2`

* Explain what reproducibility is, and, given a less reproducible analysis, explain what could be done to make the analysis more reproducible.

* Change chunk options in an `R Markdown` chunk, including `echo`, `eval`, `results`, etc.

* Make a nice-looking table with `pander()` or `kable()`

* Use bold, italic, headers, links, bullet points, numbered lists, and code font in the text of an `R Markdown` document.

* Change x and y axis labels, add a plot title and caption, change the x and y axis limits, change the colour scheme, and change the theme of a `ggplot` plot.

* Use `geom_label()` to label certain points on a `ggplot` plot.

## Week 5: Basic Programming, Piping in `magrittr`

* Identify the class of a variable in a data set and be able to change the class (we haven't covered all instances of this....like Dates, but we have covered many)

* Use classes of variables appropriately, including factors, numeric (double and integer), dates, logicals, and characters.

* Use indexing, perhaps combined with `c()`, `:`, or `-` to reference specific rows or columns of a data set.

* Explain when you can and cannot use piping. Additionally, be able to convert between the piping format and the non-piping format.

## Week 7: Data Import with `readr` and Creating a Reprex with `tibble()`

* change the options in `read_csv()` to read in a data set appropriately.

* use `tibble()` to create a reprex.

* nothing else from Week 7 will be covered in this first exam.

    